name: lafyuu
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  http: ^1.4.0
  intl: ^0.18.1
  camera: ^0.11.1
  flutter_image_gallery_saver: ^0.0.2
  image_picker: ^1.1.0
  path_provider: ^2.0.15
  flutter_local_notifications: ^19.3.0
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_svg: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
